---

language: cpp
sudo: required
dist: trusty

notifications:
    email: false

matrix:
    include:
        - os: osx
          osx_image: xcode9
          compiler: clang
        - os: linux
          compiler: gcc
          env:
              - CXX_COMPILER=g++-6
              - C_COMPILER=gcc-6
          addons:
              apt:
                  sources: ["ubuntu-toolchain-r-test"]
                  packages: ["g++-6"]
        - os: linux
          compiler: clang
          env:
              - CXX_COMPILER=clang++-6.0
              - C_COMPILER=clang-6.0
          addons:
              apt:
                  sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-trusty-6.0"]
                  packages: ["clang-6.0","clang++-6.0"]

before_install:
    - export CXX=${CXX_COMPILER}
    - export CC=${C_COMPILER}

install:
    - ./.ci/install.sh

script:
    - ./.ci/run.sh
