---

language: cpp
sudo: required
dist: trusty

notifications:
    email: false

matrix:
    include:
        - os: osx
          osx_image: xcode9
          compiler: clang
        - os: linux
          compiler: gcc
          env:
              - CXX_COMPILER=g++-6
              - C_COMPILER=gcc-6
          addons:
              apt:
                  sources: ["ubuntu-toolchain-r-test"]
                  packages: ["g++-6", "ninja-build"]
        - os: linux
          compiler: clang
          env:
              - CXX_COMPILER=clang++-5.0
              - C_COMPILER=clang-5.0
          addons:
              apt:
                  sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-trusty-5.0"]
                  packages: ["clang-5.0", "ninja-build"]

before_install:
    - export CXX=${CXX_COMPILER}
    - export CC=${C_COMPILER}

install:
    - ./.ci/install.sh

script:
    - ./.ci/run.sh
